// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    EmojioneFallenLeaf: typeof import('~icons/emojione/fallen-leaf')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Nav: typeof import('./components/Nav.vue')['default']
    NotoPottedPlant: typeof import('~icons/noto/potted-plant')['default']
    README: typeof import('./components/README.md')['default']
    TwemojiPottedPlant: typeof import('~icons/twemoji/potted-plant')['default']
  }
}

export { }
